[package]
name = "server"
version = "0.1.0"
authors = ["jD91mZM2 <LEGOlord208@krake.one>"]

[dependencies]
futures    = "0.1.15"
openssl    = "0.9.17"
tokio-core = "0.1.9"
tokio-io   = "0.1.3"
tokio-openssl = "0.1.3"
common = { path = "../common" }
