[package]
name = "server"
version = "0.1.0"
authors = ["jD91mZM2 <LEGOlord208@krake.one>"]

[dependencies]
futures    = "0.1"
openssl    = "0.9"
rusqlite   = "0.12"
tokio-core = "0.1"
tokio-io   = "0.1"
common = { path = "../common" }
